### ISSUE TITLE
BasicConvLSTMCell without sequence marker！

### ISSUE THREAD

**Issue by chuchienshu** [jiangsutx/SRN-Deblur#10]
Hi, @jiangsutx .
Given others' Convlstm implementation, like [here](https://github.com/agethen/ConvLSTM-for-Caffe), which including a **sequence marker** input for Convlstm. And it is used to decide whether discard the state(both c and h) or not. However, I do not find this point in `BasicConvLSTMCell`.
And I also noticed that you may implementated Convlstm using [this line](https://github.com/jiangsutx/SRN-Deblur/blob/master/models/model.py#L71). Therefore, I wonder that [this line](https://github.com/jiangsutx/SRN-Deblur/blob/master/models/model.py#L71) run only once in the whole train phase OR synchronous execute with [this loop](https://github.com/jiangsutx/SRN-Deblur/blob/master/models/model.py#L206)?
Thanks a lot!

**Comment by firenxygao** [comment]
@chuchienshu This is only an initialization and run only once.

**Comment by chuchienshu** [comment]
@firenxygao , Thanks for reply. If so, that means that you take the whole dataset as a consecutive sequence! I know the dataset consists of some consecutive frames,but  it totally not consecutive in the whole. Does that make sense?

**Comment by firenxygao** [comment]
@chuchienshu This method only considers different scales of a single image as sequences, not different frames.

**Comment by chuchienshu** [comment]
@firenxygao but your **lstm state** keep flow into different frames. How could this be? Why not discard the last state when input different scene frames?

**Comment by firenxygao** [comment]
@chuchienshu For each frame, the rnn_state will be initialized to zero, and start calculation from the coarsest level. I don't know why lstm state will flow into different frames. Please understand the lstm here correctly.

**Comment by chuchienshu** [comment]
@firenxygao Looks like I went astray from your first reply. I get it now. thx for your patience!
