### ISSUE TITLE
Weight Decay

### ISSUE THREAD

**Issue by DuCheng2018** [jiangsutx/SRN-Deblur#11]
Do you imply weight decay when training SRN?
I do not find weight decay in the code.

**Comment by jiangsutx** [comment]
No. We did not use that.

**Comment by DuCheng2018** [comment]
Did you have any experiments of using weight decay in SRN? 
If you have, how did the model perform?

**Comment by jiangsutx** [comment]
No. We didn't.
Weight decay is usually used when over-fitting.
We did not observe such phenomenon, so no such experiments have been conducted.

**Comment by DuCheng2018** [comment]
Have you conducted experiments about u-net structure?
I didn`t find any processing comparision with u-net in your paper.
