### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by rahul12122** [jiangsutx/SRN-Deblur#13]
how to calculate psnr of testing data ?

**Comment by csu-ist** [comment]
May be you can consider to use the function "skimage.measure.compare_psnr(im_true, im_test, data_range=None, dynamic_range =None )" .

**Comment by Courageux-J** [comment]
You should find the answer in README.MD.  You can calculate psnr of testing data using MATLAB.
### Evaluation
The quantitative results of **PSNR** and **SSIM** in the paper is 
calculated using MATLAB built-in function `psnr()` and `ssim()` based 
on the generated color results.
