### ISSUE TITLE
Can the model apply to the focal-blurred image?

### ISSUE THREAD

**Issue by csu-ist** [jiangsutx/SRN-Deblur#14]
Hi, jiangsutx:
      I know the model is trained by motion-blurred image database, and it can repaired well.
I input some focal-blurred images, the output images just increased a little in ssim/gmg/psnr(even part of images decreased). 
Maybe I need to retrain the model use focal-blurred/clear photographs?
Looking forward to your suggestions. Thanks.

**Comment by jiangsutx** [comment]
Yes.
The testing data should be the same type as training. You need to train on focal blurred photos.

**Comment by zhLawliet** [comment]
@csu-ist where can i get the focal-blurred images,thanks

**Comment by csu-ist** [comment]
@jiangsutx  Get, Thanks~

**Comment by csu-ist** [comment]
@zhLawliet   I take focal-blurred photos by myself, but I found the question is that I could not get the corresponding sharp photos, focusing and not focusing  photos dont have same field of view, and it is hard to alignment.

**Comment by zhLawliet** [comment]
@csu-ist OK，thanks
