### ISSUE TITLE
re train using previous checkpoint

### ISSUE THREAD

**Issue by rahul12122** [jiangsutx/SRN-Deblur#15]
how to train network using previous checkpoint

**Comment by dcrmg** [comment]
try to change the following code in "model.py":
`self.saver = tf.train.Saver(max_to_keep=50, keep_checkpoint_every_n_hours=1)
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

summary_op = tf.summary.merge_all()
summary_writer = tf.summary.FileWriter(self.train_dir, sess.graph, flush_secs=30)`

to:
`# training summary
summary_op = tf.summary.merge_all()
summary_writer = tf.summary.FileWriter(self.train_dir, sess.graph, flush_secs=30)

saver = tf.train.import_meta_graph(r'./checkpoints/color/deblur.model-523000.meta')
saver.restore(sess, tf.train.latest_checkpoint(r'./checkpoints/color/'))
self.saver = saver

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)`

**Comment by Williamlizl** [comment]
> try to change the following code in "model.py":
> `self.saver = tf.train.Saver(max_to_keep=50, keep_checkpoint_every_n_hours=1)
> coord = tf.train.Coordinator()
> threads = tf.train.start_queue_runners(sess=sess, coord=coord)
> 
> summary_op = tf.summary.merge_all()
> summary_writer = tf.summary.FileWriter(self.train_dir, sess.graph, flush_secs=30)`
> 
> to:
> `# training summary
> summary_op = tf.summary.merge_all()
> summary_writer = tf.summary.FileWriter(self.train_dir, sess.graph, flush_secs=30)
> 
> saver = tf.train.import_meta_graph(r'./checkpoints/color/deblur.model-523000.meta')
> saver.restore(sess, tf.train.latest_checkpoint(r'./checkpoints/color/'))
> self.saver = saver
> 
> coord = tf.train.Coordinator()
> threads = tf.train.start_queue_runners(sess=sess, coord=coord)`

I also need to change the datalist  .txt, add my own data to it?

**Comment by noranali** [comment]
> try to change the following code in "model.py": `self.saver = tf.train.Saver(max_to_keep=50, keep_checkpoint_every_n_hours=1) coord = tf.train.Coordinator() threads = tf.train.start_queue_runners(sess=sess, coord=coord)
> 
> summary_op = tf.summary.merge_all() summary_writer = tf.summary.FileWriter(self.train_dir, sess.graph, flush_secs=30)`
> 
> to: `# training summary summary_op = tf.summary.merge_all() summary_writer = tf.summary.FileWriter(self.train_dir, sess.graph, flush_secs=30)
> 
> saver = tf.train.import_meta_graph(r'./checkpoints/color/deblur.model-523000.meta') saver.restore(sess, tf.train.latest_checkpoint(r'./checkpoints/color/')) self.saver = saver
> 
> coord = tf.train.Coordinator() threads = tf.train.start_queue_runners(sess=sess, coord=coord)`

hi,thanks.your reply helps me
but is this only will be changed. i understand that you restore the model graph with value but how can i feed the training data to work with this restored graph and then save the new weights ? . please help
