### ISSUE TITLE
can the model test on cifar10dataset?

### ISSUE THREAD

**Issue by hanshan1** [jiangsutx/SRN-Deblur#18]
when i test on the cifar10 dataset ,i met the error:ValueError: Cannot feed value of shape (1, 720, 1280, 4) for Tensor u'Placeholder:0', which has shape '(1, 720, 1280, 3)'

**Comment by jiangsutx** [comment]
Please check your images, I think they contain transparency channel.
You can only use the first 3 channels.

**Comment by jiangsutx** [comment]
I think your images contain transparency channel.
You can use only first 3 channels for testing.
