### ISSUE TITLE
关于模型大小和无法用作者提供的模型继续训练的问题

### ISSUE THREAD

**Issue by wjbtju** [jiangsutx/SRN-Deblur#2]
您好，非常感谢您开源此项目的代码。我在按照您提供的方式训练模型后，得到了的模型大小是82.6MB，但是您提供的训练好的模型大小是27.5MB，并且无法加载您提供的训练好的模型继续训练，请您帮我看看问题出在哪里，万分感谢！

**Comment by jiangsutx** [comment]
I only saved the trainable parameters and ignored many other variables that are only useful in training.
You can random init your training process, and load my weight, and continue for training.
