### ISSUE TITLE
Does it work for Motion Deblur?

### ISSUE THREAD

**Issue by sanyamgirdhar** [jiangsutx/SRN-Deblur#25]
I have been training this model with my dataset of blur images and have got some results but I am not able to Deblur the Images having Motion blur. Also Is there any way for generatng dataset of Motion Blur images?

**Comment by jiangsutx** [comment]
The examples and datasets used in the paper are exactly motion blur.
But maybe not every image works well. You can also synthesize use kernels or camera paths.
