### ISSUE TITLE
Some questions on BasicConvLSTMCell

### ISSUE THREAD

**Issue by Deephome** [jiangsutx/SRN-Deblur#27]
Hi, I have some questions:

1. there are no definition for  "self._num_units" in class BasicConvLSTMCell ?
2. what's the role of "forget_bias=1.0" ? some conv_lstm implementation don't use this forget bias.

Looking forward to your reply!

**Comment by jiangsutx** [comment]
Actually I used an open-source implementation for ConvLSTM.
I think we did not use that function containing `_num_units`, so it will not cause error in practice.

You can switch to official implementation from TensorFlow instead.
[tf.contrib.rnn.ConvLSTMCell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/ConvLSTMCell)

**Comment by Deephome** [comment]
@jiangsutx Thank you for your reply!
