### ISSUE TITLE
Questions about test pictures

### ISSUE THREAD

**Issue by JusperLee** [jiangsutx/SRN-Deblur#32]
I used my own test picture and the pre-processing model provided by the author for testing, but the picture of the final result could not be opened for viewing, I wonder what is the reason

**Comment by jiangsutx** [comment]
Please at least provide some error messages for others to help you.

And the code is totally open-source with Python. 
You can check whether you image is correctly loaded, and whether the network produces correct output.

**Comment by pyl62112991** [comment]
![图片](https://user-images.githubusercontent.com/47971541/63645321-08b4cb00-c72e-11e9-8992-7db9abd9203d.png)
I used my own test picture and the pre-processing model provided by the author for testing but failed,could you help me solve the problem

**Comment by Gnaixzl** [comment]
I am experiencing the same problem.

**Comment by JusperLee** [comment]
May be the size required for the image

**Comment by jiangsutx** [comment]
This network uses encoder-decoder-like structure, the images are first downsampled and then upsampled to original size.
So in this process,  the input size should be multiples of some power of 2. 
I think it is better to first pad the image to multiples of 16, and then feed into network. The output will be correct.

I will try to put a bugfix patch in test() function.
