### ISSUE TITLE
The details of "--model=gray"

### ISSUE THREAD

**Issue by oobbppoo** [jiangsutx/SRN-Deblur#37]
Hi, in the README text, you said "--model=gray: According to our further experiments after paper acceptance, we are able to get a slightly better model by tuning parameters, even without LSTM. This model should produce visually sharper and quantitatively better results.". Could you please tell me the details of this model? What's the difference from the accepted paper?

**Comment by jiangsutx** [comment]
We just removed the LSTM module. Other parts are the same.
You can refer to our source code for more details.
