### ISSUE TITLE
About the kernel size of the deconvolution layer

### ISSUE THREAD

**Issue by oobbppoo** [jiangsutx/SRN-Deblur#38]
Hi, in your released paper, you said "all kernel sizes are set to 5", but I found that the kernel size of deconvolution layer in decoder part was set to 4, as your code written:
`deconv2_4 = slim.conv2d_transpose(deconv3_1, 64, [4, 4], stride=2, scope='dec2_4')`
`deconv1_4 = slim.conv2d_transpose(deconv2_1, 32, [4, 4], stride=2, scope='dec1_4')`
Why did you make this change? Does this make performance better?

**Comment by jiangsutx** [comment]
We use kernel size 4 for deconvolution layers. 
I remember we mentioned that in the paper.

Using kernel size 4 and stride 2 can ensure a scale factor 2x. No other special reasons.
