### ISSUE TITLE
Model link is note found.

### ISSUE THREAD

**Issue by Harry-675** [jiangsutx/SRN-Deblur#4]
Hello,I found the model link is lost,I am not sure if it's my network environment's problem. Could you upload it again?

**Comment by wjbtju** [comment]
www.xtao.website/shared_url/srndeblur_models.zip

**Comment by Harry-675** [comment]
@wjbtju Thanks!

**Comment by Harry-675** [comment]
@wjbtju Thanks for your help before.But I still can not run this.I got error like this
![image](https://user-images.githubusercontent.com/29157861/41808590-605e46be-7712-11e8-9da8-3be4d9bc2902.png)
How do you run this?

**Comment by jiangsutx** [comment]
I think you use gray model checkpoints with color model codes. You can use `--model=` to select models, it should work well.
