### ISSUE TITLE
quetion about testing

### ISSUE THREAD

**Issue by pyl62112991** [jiangsutx/SRN-Deblur#43]
I used my own test picture and the pre-processing model provided by the author for testing but failed,could you help me see this question.
![图片](https://user-images.githubusercontent.com/47971541/63645334-8a0c5d80-c72e-11e9-9877-ef3a8270a46e.png)

**Comment by shreya2000** [comment]
> I used my own test picture and the pre-processing model provided by the author for testing but failed,could you help me see this question.
> ![图片](https://user-images.githubusercontent.com/47971541/63645334-8a0c5d80-c72e-11e9-9877-ef3a8270a46e.png)

Hey , did you find solution for this ? If yes, can you please help me out?  i'm getting the same problem.
Thanks in advance.

**Comment by jiangsutx** [comment]
I think this is related to your image's resolution.

Note that we have downsample and upsample in the network for multiple times. The width and height for images should be multiples of 16 (as I remembder). 

You can crop or pad a little, then you can get correct results.
