### ISSUE TITLE
crop_size

### ISSUE THREAD

**Issue by Flyzzz** [jiangsutx/SRN-Deblur#44]
hi, could anyone tell me that what the scripts do with the crop_size(at model.py). when I run training. it shows <img_in, img_gt (4, 128, 128, 1) (4, 128, 128, 1)>, 4 is my batchsize，I set the crop_size = 128, but I don not know what is it means? Does it means input placeholders? thank you

**Comment by jiangsutx** [comment]
When doing training, a common routine is to crop a batch of images into the same size. And then concatenate them together to form a training batch.
In image processing tasks, crop is usually done in a random crop manner. That is to choose a random position in each image and then crop a size of 128*128 square patch.

**Comment by Flyzzz** [comment]
thank you  for you reply. for a 400*400 image, only 128*128 of it is used to train?

**Comment by jiangsutx** [comment]
It is `random crop'. During training, the same image will be used multiple times with different location chosen.
