### ISSUE TITLE
test on kohler dataset

### ISSUE THREAD

**Issue by SunshineJunFu** [jiangsutx/SRN-Deblur#45]
I download kohler dataset from [here](http://webdav.is.mpg.de/pixel/benchmark4camerashake/), where I save  images as JPG. Then, I use the  following command:
```bash
python run_model.py --input_path= xxx --output_path=xxxx
```
where I use the pretrained model parameters stored at the 523000th step. 

After obtaining the deblurring images, I use the `ssim` and `psnr` provided by matlab to calculate the quantitative results. The average psnr and ssim are  `19.37` and `0.74`, respectively. 

I am confused at this experimental results.  Could you provide some information how to set up the evaluation at Kohler dataset?

**Comment by noranali** [comment]
@SunshineJunFu 
hey, i have the same issue . can you help me and tell me how did you solve this problem ?
