### ISSUE TITLE
人脸老化模拟

### ISSUE THREAD

**Issue by zxcv2018** [jiangsutx/SRN-Deblur#5]
你好，我在《Generative Face Completion 》这个GitHub上看到了你的回复，了解到你在做人脸老化模拟，我刚好最近也在做这方面，有几个问题想跟你交流以下。在你GitHub主页上没有看到你的联系方式，只能通过这种方式，如有打扰还请原谅。谢谢！

**Comment by jiangsutx** [comment]
我没有做过人脸老化模拟，也不记得在那里回复过了唉。
你可以联系看看这个作者：https://github.com/yingcong/Facelet_Bank

**Comment by zxcv2018** [comment]
是别人fork一个您的项目，本来想回复他，结果弄错，回复给您，打扰到您了。非常感谢您提供的链接。谢谢




发自网易邮箱大师


在2018年07月4日 11:05，Xin Tao<notifications@github.com> 写道：

我没有做过人脸老化模拟，也不记得在那里回复过了唉。
你可以联系看看这个作者：https://github.com/yingcong/Facelet_Bank
