### ISSUE TITLE
Could not get obvious effect from the color model

### ISSUE THREAD

**Issue by ANSHUMAN87** [jiangsutx/SRN-Deblur#52]
Dear Author,
 Thanks a lot for such a great model and the results are really great in most of the cases.
But in some cases i could not find the sharpening of the images too distinguishable.
Just wanted to confirm, whether the pretrained model shared in the github, can handle focal blurred images, or it only handles motion blurred ?

Eagerly waiting for your response, TIA!

**Comment by shreya2000** [comment]
hey 

> Dear Author,
> Thanks a lot for such a great model and the results are really great in most of the cases.
> But in some cases i could not find the sharpening of the images too distinguishable.
> Just wanted to confirm, whether the pretrained model shared in the github, can handle focal blurred images, or it only handles motion blurred ?
> 
> Eagerly waiting for your response, TIA!

Hey, did you get any solution ? If yes, can you please help me? I am facing the same problem .
Thanks in advance.

**Comment by jiangsutx** [comment]
Hi, 
Yes. This model cannot handle some of the cases.
And note that our training data are only for motion blur. So the model cannot handle well focus blur.

I guess you need to prepare your own focus blur data and test on your images.

**Comment by shreya2000** [comment]
Okay thanks.

**Comment by shreya2000** [comment]
But I have a confusion if it works accurately for motion blur. I not
getting good output for motion blur images also. Did you get better output
for motion blur?
Thanks in advance.
