### ISSUE TITLE
 Cannot feed value of shape (1, 720, 1280, 4) for Tensor 'Placeholder:0', which has shape '(1, 720, 1280, 3)'

### ISSUE THREAD

**Issue by Lie-huo** [jiangsutx/SRN-Deblur#55]
hello，when i test  a 532*570 image， it happens that  “Cannot feed value of shape (1, 720, 1280, 4) for Tensor 'Placeholder:0', which has shape '(1, 720, 1280, 3)'”，what‘s the matter？How can solve this problem?

**Comment by Williamlizl** [comment]
multiple by 16 and set argument when train

**Comment by jiangsutx** [comment]
And maybe your image has 4 channels, try to convert to RGB images first: you can slice first 3 channels or use opencv
