### ISSUE TITLE
util包问题

### ISSUE THREAD

**Issue by nobody-cheng** [jiangsutx/SRN-Deblur#6]
from util.util import *
请问下这个模块是怎么安装的, 网上没有解决这个问题,谢谢

**Comment by jiangsutx** [comment]
这是这个项目内自己的文件。

**Comment by pz-AOE** [comment]
有点奇怪的是我也遇到了这个问题。只能将util下的文件放在外面才能找到...

**Comment by zhLawliet** [comment]
请问下，为什么还有这个问题“ImportError: No module named util” ，放在哪里都不行。
