### ISSUE TITLE
How to generate blured pictures?

### ISSUE THREAD

**Issue by Williamlizl** [jiangsutx/SRN-Deblur#60]

**Comment by jiangsutx** [comment]
We use GOPRO dataset for training.

This dataset uses high-frame-rate camera to capture 120 fps videos. And then average neighbouring several frames to generate blurry pictures.

**Comment by wyx2001-0615** [comment]
Hi, I am currently trying to use GoPro to generate pairs of blurred images, creating blurred images from videos I recorded myself. Could you please share the code for generating blur with GoPro? Thank you.
