### ISSUE TITLE
save_path is not a valid checkpoint

### ISSUE THREAD

**Issue by lin-peiyi** [jiangsutx/SRN-Deblur#64]
Thanks for your sharing.
How can I deal with this problem?
ValueError: The passed save_path is not a valid checkpoint: ./checkpoints\color\deblur.model-523000

**Comment by jiangsutx** [comment]
Please check whether the file exists?
If not, you need to first download the model file, using `./checkpoints/download_model.sh`

**Comment by lin-peiyi** [comment]
> Please check whether the file exists?
> If not, you need to first download the model file, using `./checkpoints/download_model.sh`

Yes,I haved downloaded it.Whether this model has to be run in linxus?Because I use win10,appearing a lot of bugs.

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints\color\deblur.model-523000
	 [[Node: save/RestoreV2_83 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_83/tensor_names, save/RestoreV2_83/shape_and_slices)]]

**Comment by sherlybe** [comment]
so, do u run it sucessfully?

**Comment by jiangsutx** [comment]
> > Please check whether the file exists?
> > If not, you need to first download the model file, using `./checkpoints/download_model.sh`
> 
> Yes,I haved downloaded it.Whether this model has to be run in linxus?Because I use win10,appearing a lot of bugs.
> 
> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints\color\deblur.model-523000
> [[Node: save/RestoreV2_83 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_83/tensor_names, save/RestoreV2_83/shape_and_slices)]]

Maybe it is because the path `./checkpoints\color\deblur.model-523000` uses a mix of `/` and `\` ?

**Comment by lin-peiyi** [comment]
> so, do u run it sucessfully?

**Comment by lin-peiyi** [comment]
> so, do u run it sucessfully?
 
I can't open the  ./checkpoints/download_model.sh in win10,so I have used ubuntu to run it,that's ok.
So maybe you can have a try.

**Comment by lin-peiyi** [comment]
> so, do u run it sucessfully?

I can't open the ./checkpoints/download_model.sh in win10,so I have used ubuntu to run it,that's ok.
So maybe you can have a try. @sherlybe

**Comment by lin-peiyi** [comment]
> > > Please check whether the file exists?
> > > If not, you need to first download the model file, using `./checkpoints/download_model.sh`
> > 
> > 
> > Yes,I haved downloaded it.Whether this model has to be run in linxus?Because I use win10,appearing a lot of bugs.
> > NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./checkpoints\color\deblur.model-523000
> > [[Node: save/RestoreV2_83 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_83/tensor_names, save/RestoreV2_83/shape_and_slices)]]
> 
> Maybe it is because the path `./checkpoints\color\deblur.model-523000` uses a mix of `/` and `\` ?


Thank you very much.I can run it in ubuntu.
