### ISSUE TITLE
HOW CAN I DO TESTING USING GPU??

### ISSUE THREAD

**Issue by KainatRiaz98** [jiangsutx/SRN-Deblur#67]
I passed the argument --gpu=0.
I have cuda installed.
 I even tried to  run  it on google colab still it displays "Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA" showing it is running on CPU.
I need to do tesing on thousands of images and CPU testing is too slow.
am I doing anything wrong? please help.

**Comment by noobtoob4lyfe** [comment]
I'm having the same issue.  Did you ever find a solution?  This issue should probably remain open until it's fixed no?

**Comment by KainatRiaz98** [comment]
I did find the solution. Firstly, instead of this repository I used ' https://github.com/thisishardik/SRN-Deblur' . it has support for tensor flow 2.x . secondly passing arguments does not work for this repository for some reason so just physically change in the script run_model.py. I was able to do testing on GPU by making these changes.

**Comment by noobtoob4lyfe** [comment]
Thanks for the response.  Unfortunately I got into the weeds a bit here with new errors.   When I install the latest gpu version or go back to 1.14 I get the same error.

"File "C:\Users\importon\Documents\SRN-Deblur-master\models\model.py", line 10, in <module>
    import tensorflow.contrib.slim as slim
ModuleNotFoundError: No module named 'tensorflow.contrib'"

Did you experience this?

**Comment by KainatRiaz98** [comment]
Try '!pip install tf_slim'

**Comment by noranali** [comment]
> I passed the argument --gpu=0. I have cuda installed. I even tried to run it on google colab still it displays "Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA" showing it is running on CPU. I need to do tesing on thousands of images and CPU testing is too slow. am I doing anything wrong? please help.

can you share google colab please ?

**Comment by KainatRiaz98** [comment]
send me your email address
